/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.sap.cx.boosters.easy.demo

class Library {
    boolean someLibraryMethod() {
        true
    }
}

new Library();